# -*- coding: utf-8 -*-
"""FYPGetLinksScraping.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mhI7qx5owHexFNSmsv8LD2FomaARUWFR

Importing Google Search. To get results for a search term for each term.
"""

!pip install google
!pip install pandas

from google.colab import auth
auth.authenticate_user()

import gspread
from google.auth import default
# from oauth2client.client import GoogleCredentials
creds, _ = default()
gc = gspread.authorize(creds)
# gc = gspread.authorize(GoogleCredentials.get_application_default())

try:
    from googlesearch import search
except ImportError:
    print("No module named 'google' found")

"""Read Excel Sheet and Save info"""

import pandas as pd
import matplotlib.pyplot as plt
wb = gc.open_by_url('https://docs.google.com/spreadsheets/d/15bsqYazKmstMi987xM3wPC2wZNQbcZS8DmXPv2x_wec/edit#gid=0')
sheet = wb.worksheet('Sheet1')
data = sheet.get_all_values()
products = pd.DataFrame(data)
products.columns = products.iloc[0]
products = products.iloc[1:]
# products = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vT4DFCSLVHvOGzj_1zqg_zW6j4kf60bZC3a3AC64oBQUni7pUfepIDoXrsttUqErtds0glh4i15L2GR/pub?gid=0&single=true&output=csv")

products

products["Product"][1]

"""Get one Google Search result from each product"""

# Function to return product names that contain only the product name and not the quantity
# e.g "Dalda Cooking Oil 1L" would now be "Dalda Cooking Oil"
import re
def prodname(prod1):
  m = re.search(r"\d", prod1)
  # print(m)
  if(m is not None):
    st = (m.start()-1)
    prod2 = prod1[0:st]
    return prod2
  return prod1
# for prod in products["Product"]:
#   print(prodname(prod))

import numpy
# Sites which contain ingredient information
places=["openfoodfacts.org","grocerapp.pk","24mycart.pk","carrefour.pk","carrefouruae.com","orbis.pk","adams.pk"]
# Non Edible food categories
nonedible = ["Detergent","Soap"]
for ind in products.index:
  # call prodname function
  prodcomp = prodname(products['Product'][ind])
  # Write search query e.g "Olpers Milk Ingredients:"
  prod = prodcomp + " Ingredients: "
  # Write bool query to get only the first search result  
  f = 0

  # Keeping limit for finding sites(for debuging purposes)
  # if ind == 31:
  #   break

  # Detects food items and search their urls
  if any(ed not in products['Category'][ind] for ed in nonedible):
    # print(prod)
    # Detect rows that have no links
    if(products['Link'][ind] == ""):
      # print(prod,"==",row[1],"==",row[2])
      # Gets 10 search results
      for j in search(prod, num=10, stop=10):
        # If search result matches the sites mentioned in the places array
        if any(pl in j for pl in places):
          # If result found
          if(f==0):
            print(ind,prodcomp,j)
            # Update to CSV
            products.loc[ind, 'Link'] = j
            
            f = 1

"""Updates to Google Sheet file"""

for ind in products.index:
  if(products['Link'][ind]!=""):
    # Get Specific cell 
    c = 'C' + str(ind+1)
    # Update to that cell
    sheet.update(c,products['Link'][ind])