# -*- coding: utf-8 -*-
"""FYPLabelling.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1awlfSyoJQHHlTu0TiJ6ExPmvYFVHkzoz
"""

from google.colab import auth
auth.authenticate_user()

import gspread
from google.auth import default
# from oauth2client.client import GoogleCredentials
creds, _ = default()
gc = gspread.authorize(creds)
# gc = gspread.authorize(GoogleCredentials.get_application_default())

import pandas as pd
wb = gc.open_by_url('https://docs.google.com/spreadsheets/d/15bsqYazKmstMi987xM3wPC2wZNQbcZS8DmXPv2x_wec/edit#gid=0')
sheet = wb.worksheet('Sheet1')
data = sheet.get_all_values()
products = pd.DataFrame(data)
products.columns = products.iloc[0]
products = products.iloc[1:]

products['Issue']

"""Label each product with their particular Health Issue"""

lactose = ["Milk","Milk Solids","Lactate","Butter","Yogurt","Cream","Cheese"]
pascaterian = ["Meat","Chicken","Poultry","Beef"]
found = 0
for ind in products.index:
  issue_list = ""
  # For Lactose
  for l in lactose:
    if(l.lower() in products['Ingredient'][ind].lower()):
      issue_list += "Lactose"
      break
  # For Lactose
  for p in pascaterian:
    if(p.lower() in products['Ingredient'][ind].lower()):
      issue_list += " Pascaterian"
      break
  ingredient = products['Ingredient'][ind]
  # print(issue_list)
  products.loc[ind, 'Issue'] = issue_list

products

for ind in products.index:
  # if(products['Issue'][ind]!=""):
  # Get Specific cell 
  c = 'E' + str(ind+1)
  # Update to that cell
  sheet.update(c,products['Issue'][ind])