name: ashiya_o_rasad
description: Our FYP Project

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: 3.0.0
  built_collection: 5.1.1
  built_value: 8.1.3
  cached_network_image: 3.1.0+1
  cloud_firestore: ^2.5.4
  firebase_auth: ^3.2.0
  firebase_core: ^1.10.0
  font_awesome_flutter: 8.11.0
  google_fonts: ^2.1.0
  google_sign_in: ^4.5.9
  intl: 0.17.0
  json_path: 0.2.1
  json_serializable: 4.1.4
  page_transition: 2.0.4
  rxdart: 0.26.0
  sign_in_with_apple: 3.3.0
  timeago: 3.1.0
  url_launcher: 6.0.15

  flutter_audio_recorder2: ^0.0.2
  firebase_storage: ^10.2.9
  http: ^0.13.4

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  build_runner: 2.1.5
  built_value_generator: 8.1.1
  flutter_launcher_icons:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter_icons:
  android: true
  ios: true
  image_path_ios: "assets/images/appstore.png"
  image_path_android: "assets/images/playstore.png"

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/images/welcome.jpg
    - assets/images/google.png
    - assets/images/categories/Beverages.png
    - assets/images/categories/Condiments.png
    - assets/images/categories/Spices.png
    - assets/images/categories/Detergent.png
    - assets/images/categories/Fats and Olis.png
    - assets/images/categories/Flour.png
    - assets/images/categories/Processed.png
    - assets/images/categories/Processed Food.png
    - assets/images/categories/Spices.png
    - assets/images/categories/Dairy.png
    - assets/images/Milk.jpg
    - assets/images/Tea.png
    - assets/images/Products/Lipton Yellow Label.png
    - assets/images/Products/SB Super.png
#    - assets/images/Products/Surf Excel.png
    - assets/images/Products/Dalda Canola Oil Pouch.png
    - assets/images/Products/Olpers.png
#    - assets/images/Products/Dawn.png
#    - assets/images/Products/Ariel.png
    - assets/images/signup.jpg
    - assets/images/categories/Fats and Oil.png
    - assets/images/ProductTypes/Ariel.png
    - assets/images/ProductTypes/Bread.png
    - assets/images/ProductTypes/Cardamom.png
    - assets/images/ProductTypes/Dalda.png
    - assets/images/ProductTypes/Egg.png
    - assets/images/ProductTypes/Gram.png
    - assets/images/ProductTypes/Milk.png
    - assets/images/ProductTypes/Pickle.png
    - assets/images/ProductTypes/Salt.png
    - assets/images/ProductTypes/Sugar.png
    - assets/images/ProductTypes/SurfExcel.png
    - assets/images/ProductTypes/Tea.png
    - assets/images/ProductTypes/Turmeric.png
    - assets/images/ProductTypes/Wheat.png
    - assets/images/Products/Ariel 1kg.png
    - assets/images/Products/Ariel 500g.png
    - assets/images/Products/Bread and Beyond Plain.png
    - assets/images/Products/Brooke Bond.png
    - assets/images/Products/Dalda Canola Oil Pouch.png
    - assets/images/Products/Dawn Bran.png
    - assets/images/Products/Dawn Multigrain.png
    - assets/images/Products/Dawn Plain.png
    - assets/images/Products/Dawn Whole Wheat.png
    - assets/images/Products/Farm Fresh Golden.png
    - assets/images/Products/Farm Fress Omega 3.png
    - assets/images/Products/Lipton Yellow Label.png
    - assets/images/Products/Lipton.png
    - assets/images/Products/Mezan Green Tea.png
    - assets/images/Products/nestle-yogurt.png
    - assets/images/Products/Nestle.png
    - assets/images/Products/Olpers.png
    - assets/images/Products/Olpers_Milk.png
    - assets/images/Products/prema-yogurt.png
    - assets/images/Products/Prema.png
    - assets/images/Products/SB Super 12.png
    - assets/images/Products/SB Super 6.png
    - assets/images/Products/SB Super.png
    - assets/images/Products/SB_Eggs.png
    - assets/images/Products/Surf Excel 1kg.png
    - assets/images/Products/Surf Excel 500g.png
    - assets/images/Products/Tapal Danedar.png
    - assets/images/Products/Tapal Tezdum.png
    - assets/images/Products/Vital Tea Pouch.png
    - assets/images/Products/Dalda Sunflower Oil.png

  # - assets/videos/
  # - assets/audios/
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
